version: "3.0"

x-logging: &default-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/api/prom/push"
    labels: namespace,service_name
    mode: non-blocking
    loki-retries: "1"
    loki-max-backoff: "800ms"
    loki-relabel-config: |
      - action: replace
        source_labels: ["namespace","compose_service"]
        separator: "/"
        target_label: job
      - action: replace
        source_labels: ["container_name"]
        target_label: instance

volumes:
  prometheus_data: {}

services:
  app:
    image: grafana/tns-app:842bd3b
    command:
      - "-log.level=debug"
      - "http://db"
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    environment:
      JAEGER_ENDPOINT: "http://tempo:14268/api/traces"
      JAEGER_TAGS: job=tns/app
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
      service_name: app
    logging: *default-logging
  loadgen:
    image: grafana/tns-loadgen:842bd3b
    command:
      - "-log.level=debug"
      - "http://app"
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    environment:
      JAEGER_ENDPOINT: "http://tempo:14268/api/traces"
      JAEGER_TAGS: job=tns/loadgen
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
      service_name: loadgen
    logging: *default-logging
  db:
    image: grafana/tns-db:842bd3b
    command:
      - "-log.level=debug"
    ports:
      - 0.0.0.0:8000:80
    environment:
      JAEGER_ENDPOINT: "http://tempo:14268/api/traces"
      JAEGER_TAGS: job=tns/db
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: tns
      service_name: db
    logging: *default-logging
  grafana:
    image: grafana/grafana-dev:11.1.0-173403
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall traceqlEditor traceQLStreaming metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app,https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-exploretraces-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      namespace: monitoring
      service_name: grafana
    logging: *default-logging
  loki:
    image: grafana/loki:main-e9b6ce9
    environment:
      LOG_CLUSTER_DEPTH: "8"
      LOG_SIM_TH: "0.3"
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml --pattern-ingester.enabled=true
    restart: on-failure
    labels:
      namespace: monitoring
      service_name: loki
    logging: *default-logging
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=exemplar-storage"
    expose:
      - 9090
    labels:
      namespace: monitoring
      service_name: prometheus
    logging: *default-logging
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9411:9411" # zipkin
    labels:
      namespace: monitoring
      service_name: tempo
    logging: *default-logging
  # generator:
  #   build:
  #     context: ./generator
  #   command: -url http://loki:3100/loki/api/v1/push
